/* TRIGGER DE AUDITORIA */

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

INSERT INTO PRODUTO VALUES (NULL,'LIVRO MODELAGEM',720.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO SQL',430.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO BI',750.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO MYSQL',699.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO ORACLE',545.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO C#',850.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO C',900.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO C++',650.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO F#',400.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO PYTHON',1300.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO GOLANG',150.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO ASP.NET',499.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO .NET',520.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO DBA',75.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO HTML/CSS/JAVASCRIPT',130.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO JAVA',660.00);

CREATE DATABASE BACKUP;

USE BACKUP;


/*QUANDO*/
SELECT NOW(); --MOSTRA A HORA ATUAL--
/*QUEM*/
SELECT CURRENT_USER(); --MOSTRA O USUARIO LOGADO @ SERVIDOR--


CREATE TABLE BKP_PRODUTO(
	IDBKP_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

DELIMITER #

CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,NEW.VALOR,NOW(),CURRENT_USER(),'U');
END#

DELIMITER ;

--TESTANDO--

UPDATE PRODUTO SET VALOR = 490.00 WHERE IDPRODUTO = 4;

--VERIFICANDO--

SELECT * FROM PRODUTO;

SELECT * FROM BACKUP.BKP_PRODUTO;
