/* FUNCOES DE AGREGACAO NUMERICAS */

CREATE TABLE vendedores(
	IdVendedor INT PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(30),
	Sexo CHAR(1),
	Janeiro FLOAT(10,2),
	Fevereiro FLOAT(10,2),
	Marco FLOAT(10,2)
);

INSERT INTO vendedores VALUES(NULL,'CARLOS','M',76234.79,88346.87,7753.90);
INSERT INTO vendedores VALUES(NULL,'MARIA','F',6548.55,16598.54,4841.20);
INSERT INTO vendedores VALUES(NULL,'ANTONIO','M',654654.45,12358.81,32135.51);
INSERT INTO vendedores VALUES(NULL,'CLARA','F',32135.33,48484.22,32156.36);
INSERT INTO vendedores VALUES(NULL,'ANDERSON','M',65468.21,11513.32,14852.44);
INSERT INTO vendedores VALUES(NULL,'IVONE','F',9575.21,21215.25,21546.00);
INSERT INTO vendedores VALUES(NULL,'JOAO','M',32131.15,78753.36,8496.32);
INSERT INTO vendedores VALUES(NULL,'CELIA','F',152253.00,546549.66,84896.65);

/* MAX - TRAZ O VALOR MAXIMO DE UMA COLUNA */

SELECT MAX(Fevereiro) AS MAIOR_FEV
FROM vendedores;

/* MIN - TRAZ O VALOR MINIMO DE UMA COLUNA */

SELECT MIN(Fevereiro) AS MENOR_FEV
FROM vendedores;

/* AVG - TRAZ O VALOR MEDIO DE UMA COLUNA */

SELECT AVG(Fevereiro) AS MEDIA_FEV
FROM vendedores;

/* VARIAS FUNCOES */

SELECT MAX(Janeiro) AS MAX_JAN,
	   MIN(Janeiro) AS MIN_JAN,
	   AVG(Janeiro) AS MED_JAN
FROM vendedores;

/* TRUNCATE */

SELECT MAX(Janeiro) AS MAX_JAN,
	   MIN(Janeiro) AS MIN_JAN,
	   TRUNCATE(AVG(Janeiro),2) AS MED_JAN
FROM vendedores;

/* AGREGANDO COM SUM() */

SELECT SUM(Janeiro) AS TOTAL_JAN
FROM vendedores;

SELECT SUM(Janeiro) AS TOTAL_JAN,
	   SUM(Fevereiro) AS TOTAL_FEV,
	   SUM(Marco) AS TOTAL_MAR
FROM vendedores;

/* VENDAS POR SEXO */

SELECT Sexo, SUM(Marco) AS TOTAL_MARCO
FROM vendedores
GROUP BY Sexo;




































