/* ORGANIZACAO DE CHAVES - CONSTRAINT (REGRA) */

CREATE TABLE JOGADOR(
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

CREATE TABLE TIMES(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	ID_JOGADOR INT,
	FOREIGN KEY (ID_JOGADOR) REFERENCES JOGADOR(IDJOGADOR)
);

INSERT INTO JOGADOR VALUES(NULL, 'JOAO CANHAO');
INSERT INTO TIMES VALUES(NULL, 'SPORT',1);


SHOW DATABASES;
-- COM O COMANDO ACIMA, VEREMOS AS DATABASES: mysql, information_schema, performance_schema... --
-- ESSAS SAO BASES DE DADOS CHAMADAS DE 'DICIONARIO DE DADOS', CRIADO NA INSTALACAO DO MYSQL. --


/* -------------------------------------------------------------------------------------------------------------------- */

/* ORGANIZANDO CHAVES E ACOES DE CONSTRAINTS */

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);



/* DICIONARIO DE DADOS */ -- GUARDA OS METADADOS, QUA SAO OS DADOS DOS DADOS, DADOS ORGANIZADORES --

SHOW DATABASES; -- information_schema, mysql e performance_schema pertencem ao DICIONARIO. --

-- PROCURANDO CONSTRAINTS --

USE INFORMATION_SCHEMA;

STATUS;

SHOW TABLES; -- FOI ACHADA A 'TABLE_CONSTRAINTS' --

DESC TABLE_CONSTRAINTS;

-- DO RESULTADO QUERO SABER: CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_NAME E CONSTRAINT_TYPE --

SELECT CONSTRAINT_SCHEMA AS 'BANCO',
	   CONSTRAINT_NAME AS 'NOME',
	   TABLE_NAME AS 'TABELA',
	   CONSTRAINT_TYPE AS 'TIPO'
FROM TABLE_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'COMERCIO';


/* APAGANDO CONSTRAINTS */

USE COMERCIO;

ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE;

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);
