/* SUBQUERIES */

/* QUAL VENDEDOR VENDEU MENOS EM MARCO, QUAL VENDEU MAIS E OS QUE VENDEREAM MAIS QUE A 
	MEDIA DE FEVEREIRO */

SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

SELECT NOME, FEVEREIRO
FROM VENDEDORES
WHERE FEVEREIRO = (SELECT MAX(FEVEREIRO) FROM VENDEDORES);

SELECT NOME, FEVEREIRO
FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

/* --------------------------------------------------------------------------------------- */

/* OPERACOES EM LINHA */

SELECT NOME,
	   JANEIRO,
	   FEVEREIRO,
	   MARCO,
	   TRUNCATE((JANEIRO + FEVEREIRO + MARCO),2) AS 'TOTAL',
	   TRUNCATE(((JANEIRO + FEVEREIRO + MARCO)/3),2) AS 'MEDIA'
FROM VENDEDORES;

/* APLICANDO PORCENTAGEM */

SELECT NOME,
	   JANEIRO,
	   FEVEREIRO,
	   MARCO,
	   (JANEIRO + FEVEREIRO + MARCO) AS 'TOTAL',
	   TRUNCATE((JANEIRO + FEVEREIRO + MARCO),2)*0.25 AS 'DESCONTO 25%',
	   TRUNCATE(((JANEIRO + FEVEREIRO + MARCO)/3),2) AS 'MEDIA'
FROM VENDEDORES;