/* TRIGGERS  */

-- ESTRUTURA --
CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW --FOR EACH ROW--
BEGIN
	--(ANY COMMAND SQL)--
END;	

/*------------------------------------------------------------------------------------------------------------------*/

CREATE DATABASE TRIGGERS_AULA;

USE TRIGGERS_AULA;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(30)
);

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);


/* CRIANDO A TRIGGER */

DELIMITER #

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_USUARIO VALUES(NULL,OLD.IDUSUARIO,OLD.NOME,OLD.LOGIN);
END
#

INSERT INTO USUARIO VALUES (NULL,'ANDRADE','ANDRADE2009','HEXACAMPEAO');

DELETE FROM USUARIO WHERE IDUSUARIO = 1#

DELIMITER ;

