-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 13:06:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PROJETO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PROJETO` ;

-- -----------------------------------------------------
-- Schema PROJETO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PROJETO` DEFAULT CHARACTER SET utf8 ;
USE `PROJETO` ;

-- -----------------------------------------------------
-- Table `PROJETO`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROJETO`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `PROJETO`.`Cliente` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(30) NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  `CPF` INT(11) NOT NULL,
  `Telefone` VARCHAR(30) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
